### ISSUE TITLE
tesr2

### ISSUE THREAD

**Issue by mohitjain20** [opencodeiiita/opencodebot#29]
drtreyre

**Comment by mohitjain20** [comment]
@opencodebot or 1

**Comment by mohitjain20** [comment]
@opencodebot  unclaim @opencodebot claim

**Comment by mohitjain20** [comment]
@opencodebot help

**Comment by DreamyPhobic** [comment]
[Instructions](https://github.com/opencodeiiita/opencodebot/blob/master/USAGE.md)
