### ISSUE TITLE
Create Pull request and issue template.

### ISSUE THREAD

**Issue by DreamyPhobic** [opencodeiiita/opencodebot#33]
Look over some good organization's template, and create for our project too.

**Comment by aasthakasera** [comment]
@opencodebot claim

**Comment by aasthakasera** [comment]
@opencodebot claim

**Comment by aasthakasera** [comment]
Actually, I have to add template in this project

**Comment by DreamyPhobic** [comment]
Yes, add those in .github folder.

**Comment by DreamyPhobic** [comment]
You can join opencodebot stream on our zulip channel https://opencode.zulipchat.com for discussions.

**Comment by aasthakasera** [comment]
Ok

**Comment by helios1101** [comment]
Is this issue resolved ?? Can I work if it is hasn't?
